name: snake_game
description: Final Stable Build - Snake IO Pro with full Assets.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # مكتبات السحابة وحفظ البيانات
  shared_preferences: ^2.2.3

  # مكتبة الصوت
  audioplayers: ^5.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # أداة توليد الأيقونات
  flutter_launcher_icons: ^0.13.1

# إعدادات أيقونة التطبيق
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/game_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # تعريف كافة الصور والأصوات
  assets:
    - assets/head.png
    - assets/body.png
    - assets/tail.png
    - assets/forest.png
    - assets/icon/game_icon.png
    - assets/audio/music.mp3
    - assets/audio/eat.mp3
    - assets/audio/die.wav
