name: snake_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/game_icon.png"

flutter:
  uses-material-design: true
  
  # تعريف الملفات والمجلدات
  assets:
    - assets/icon/
    - assets/audio/
    # تعريف صور الثعبان (PNG للشفافية)
    - assets/head.png
    - assets/body.png
    - assets/tail.png
    # تعريف خلفيات المستويات (البيئات)
    - assets/forest.png
    - assets/desert.jpg
    - assets/snow.jpg
