name: snake_game
description: Final Stable Version.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  yandex_mobileads: ^7.11.0 # إصدار مستقر
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.3
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/head.png
    - assets/body.png
    - assets/tail.png
    - assets/forest.png
    - assets/desert.jpg
    - assets/snow.jpg
    - assets/audio/music.mp3
    - assets/audio/eat.mp3
    - assets/audio/die.wav
